### ISSUE TITLE
production build still want to load files from localhost

### ISSUE THREAD

**Issue by aquafun20** [chasegiunta/craft-vue#28]
I upgraded my vue application and integrated vuex and vue router. Everything looks fine but after running `npm run build` i get a error:
![74011420-17afd280-4988-11ea-807f-49354995a67f](https://user-images.githubusercontent.com/53934304/74012939-ab36d280-498b-11ea-9d69-eb2137b6117d.jpg)

This happens only on my `<router-view />` template and not where i just include a component. 
If I try to change the publicPath settings in the vue.config.js to /dist/ the build looks fine but i can't work anymore with `npm run dev` because it tries now to load everything from `http//localhost:8080/dist/ `

Overall i can just open my created app-legacy.js file and change `http//localhost:8080` to `/dist/`and it works but i think this isn't a good solution.

**Comment by chasegiunta** [comment]
@aquafun haven't incorporated vue-router into this yet. Do you happen to have a repro repo by chance?

**Comment by aquafun20** [comment]
I solved it by `publicPath: production ? "/dist/" : "/",`
it is generally a better practice to do it like this.

**Comment by chasegiunta** [comment]
Good to hear! Difficult for me to recall, but I think that change was made because depending on where you're serving assets, that public path also needs to change. For us in non-spa world, it was making more sense to serve our assets _not_ in `/dist/` because it avoids them being overwritten on build. But good to note. You're in a bit of a difference case, since you're going the SPA route with vue-router
